NOVA = ["Nova","nova","Noba","noba","Nowa","nowa"]
MASTER_CONTROL  = "master control"
ACTIVATE = "activate"
DEACTIVATE = "deactivate"
LAUNCH = ["launch gesture recognition","start gesture recognition","enable gesture recognition","1"] 
STOP = ["stop gesture recognition","stop gesture control","disable gesture recognition","0"]
CREATION =["who made you","who created you"]
Okay = ["how are you","are you ok"]
NEWS = ["news","headlines"]
#SHUTDOWN = ["log off","sign out","switch off","shutdown"]
FINE = ["i am fine","i am good","fine"]
PASTE = ["pest","paste"]
BYE = ["bye","by","see you again"]
EXIT = ["exit","terminate"]
